framework:
  messenger:

    serializer:
      default_serializer: messenger.transport.symfony_serializer

    transports:
      async: '%env(MESSENGER_TRANSPORT_DSN)%'

    routing:
      'App\Common\Message\OrderAccepted': async
      'App\Common\Message\OrderDeclined': async

    buses:
      default.bus:
        default_middleware:
          enabled: true
          allow_no_handlers: true
